# TerraVision mobil — fiziksel cihaz / geliştirme ağı kurulumu
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $root

function Get-LanIPv4 {
  $addrs = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object {
      $_.IPAddress -notlike '127.*' -and
      $_.IPAddress -notlike '169.254.*' -and
      $_.PrefixOrigin -ne 'WellKnown'
    } |
    Sort-Object -Property InterfaceMetric, PrefixLength
  if ($addrs) {
    return $addrs[0].IPAddress
  }
  return '192.168.1.1'
}

$lanIp = Get-LanIPv4
$apiUrl = "http://${lanIp}:5090"
$metroPort = if ($env:REACT_NATIVE_PACKAGER_PORT) { $env:REACT_NATIVE_PACKAGER_PORT } else { '8082' }

$configPath = Join-Path $root 'src\config\api.config.local.ts'

& (Join-Path $PSScriptRoot 'write-android-sdk-path.ps1') | Out-Null
. (Join-Path $PSScriptRoot 'android-sdk-env.ps1')

$sdk = Enable-AndroidSdkOnPath -MobileRoot $root
if ($sdk) {
  Write-Host "Android SDK: $sdk"
}

$adbExe = Get-AdbExecutable -MobileRoot $root
$devices = @()
$usbDeviceConnected = $false
if ($adbExe) {
  Write-Host "adb: $adbExe"
  $devices = @(& $adbExe devices 2>$null | Select-String -Pattern '\tdevice$')
  $usbDeviceConnected = $devices.Count -gt 0
}

$connectMode = if ($usbDeviceConnected) { 'usb' } else { 'wifi' }
$configContent = @"
/** Generated by npm run setup:device at $((Get-Date).ToString('yyyy-MM-dd HH:mm')) */
/** usb = localhost + adb reverse (USB telefon). wifi = ayni agda PC IP. */
export const API_CONNECT_MODE = '$connectMode' as 'wifi' | 'usb' | 'emulator';

export const API_URL_OVERRIDE = '$apiUrl';
"@
[System.IO.File]::WriteAllText($configPath, $configContent)
Write-Host "Yazildi: $configPath"
Write-Host "API modu: $connectMode ($(if ($connectMode -eq 'usb') { 'http://localhost:5090 + adb reverse' } else { $apiUrl }))"

if ($adbExe) {
  foreach ($line in $devices) {
    $serial = ($line -split '\s+', 2)[0]
    if (-not $serial) { continue }
    & $adbExe -s $serial reverse tcp:5090 tcp:5090 2>$null | Out-Null
    & $adbExe -s $serial reverse "tcp:$metroPort" "tcp:$metroPort" 2>$null | Out-Null
    if ($metroPort -ne '8081') {
      & $adbExe -s $serial reverse tcp:8081 tcp:8081 2>$null | Out-Null
    }
    Write-Host "adb reverse (cihaz $serial): API 5090, Metro $metroPort"
  }
  if (-not $devices.Count) {
    Write-Warning "adb bulundu ama bagli cihaz yok. USB hata ayiklama acik mi, kablo takili mi kontrol edin."
  }
} else {
  Write-Warning @"
adb bulunamadi. Android Studio > SDK Manager > SDK Tools > 'Android SDK Platform-Tools' yuklu olsun.
Beklenen yol: $env:LOCALAPPDATA\Android\Sdk\platform-tools\adb.exe
"@
}

Write-Host ""
Write-Host "=== Sonraki adimlar ==="
Write-Host "1. API (proje kokunde):  dotnet run --launch-profile http"
Write-Host "   API tum aglardan dinlemeli: http://0.0.0.0:5090"
Write-Host "2. Metro:               npm start"
Write-Host "3. Uygulamayi yukle:     npm run android:win"
Write-Host ""
Write-Host "USB takiliyken otomatik usb modu (localhost + adb reverse) kullanilir."
Write-Host "Sadece Wi-Fi ile: api.config.local.ts icinde API_CONNECT_MODE = 'wifi' yapin."
